proxy_cache mycache;

proxy_cache_valid 200 302 15m;
proxy_cache_valid 404     1m;

# GET and HEAD are cached by default
proxy_cache_methods GET HEAD;

# Do not convert HEAD into GET
proxy_cache_convert_head off;

# Since head conversion is disabled, the request_method is included in the proxy_cache_key
proxy_cache_key  "$scheme$proxy_host$request_method$request_uri$is_args$args";

# Lock the cache so that only one request can populate it at a time
proxy_cache_lock    on;
proxy_cache_revalidate on;

# Set back a nice HTTP Header to indicate what the cache status was
add_header X-Proxy-Cache $upstream_cache_status;

