user nginx;
pid /var/run/nginx.pid;

worker_processes 16;
worker_rlimit_nofile 20000;
events {
    worker_connections 4096;
    use epoll;
}

http {
    proxy_cache_path /var/cache/nginx keys_zone=mycache:512m max_size=100g levels=1:2 inactive=24h
                     loader_sleep=10ms manager_files=4000 manager_threshold=200m manager_sleep=100ms;
    map $http_cache_control $cache_bypass {
        no-cache   1;
    }
    proxy_cache_bypass $cache_bypass;

    # Increase in-memory buffers (this assumes we have a lot of RAM)
    proxy_buffer_size 64k;
    proxy_buffers 32 128k;
    proxy_busy_buffers_size 256k;
    # Disable temp file buffering (or we run out of space when downloading huge files)
    proxy_max_temp_file_size 0;

    # Timeouts
    proxy_connect_timeout 10s;
    proxy_read_timeout 60s;
    proxy_send_timeout 300s;

    # Only return Nginx in server header
    server_tokens off;

    server {
        server_name s3.janelia.org;
        listen 443 ssl default_server;
        listen [::]:443 ssl;
        http2 on;

        # SSL config
        ssl_certificate /certs/wildcard.janelia.org/cert.crt;
        ssl_certificate_key /certs/wildcard.janelia.org/cert.key;
        include /etc/nginx/conf/ssl.conf;

        location = / {
            include /etc/nginx/conf/proxy_cache.conf;
            include /etc/nginx/conf/proxy_pass.conf;
        }

        location / {
            include /etc/nginx/conf/proxy_cache.conf;
            include /etc/nginx/conf/proxy_pass.conf;
        }
    }

    upstream x2s3 {
        zone upstreams 64K;
        server x2s3:8000;
        keepalive 16;
    }
}
